name: Build

on:
  push:
    branches:
      - main

jobs:
  set-env:
    runs-on: windows-latest
    outputs:
      VST2_SDK_PATH: ${{ steps.set-env.outputs.VST2_SDK_PATH }}
    steps:
      - name: Set VST2_SDK_PATH environment variable
        id: set-env
        run: echo "##[set-output name=VST2_SDK_PATH;]${{ github.workspace }}\VST_SDK\vst3sdk"

  check-dependencies:
    runs-on: windows-latest
    needs: set-env
    steps:

      - name: Check if Visual Studio is installed
        id: check-visual-studio
        run: |
          $vsPath = "${env:ProgramFiles(x86)}\Microsoft Visual Studio\Installer\vswhere.exe"
          $vsWhereOutput = & $vsPath -latest -property installationPath
          if (-not $vsWhereOutput) {
            Write-Host "Visual Studio is not installed."
            exit 1
          }

  build:
    runs-on: windows-latest
    needs: [set-env, check-dependencies]
    env:
      VST2_SDK_PATH: ${{ needs.set-env.outputs.VST2_SDK_PATH }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CMake
        run: |
          mkdir cmake
          Invoke-WebRequest -Uri "https://github.com/Kitware/CMake/releases/download/v3.21.0/cmake-3.21.0-windows-x86_64.zip" -OutFile "cmake/cmake.zip"
          Expand-Archive -Path cmake/cmake.zip -DestinationPath cmake
          $cmakeBinPath = "$(Get-Location)/cmake/bin"
          if (-not ([System.Environment]::GetEnvironmentVariable("Path", "Machine") -split ";" | Select-String -SimpleMatch $cmakeBinPath)) {
            $newPath = $cmakeBinPath + ";" + [System.Environment]::GetEnvironmentVariable("Path", "Machine")
            [System.Environment]::SetEnvironmentVariable("Path", $newPath, "Machine")
          }

      - name: Set up Visual Studio 2022
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 'latest'

      - name: Configure project
        run: |
          $DEFS = ""
          cmake -G "Visual Studio 16 2019" -A "x64" -B build
          echo 'set(VST2_SDK_PATH "${{ env.VST2_SDK_PATH }}")' >> build\CMakeLists.txt

      - name: Build project
        run: |
          cd D:\a\sonobus\sonobus
          .\buildcmake.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Release-Artifacts
          path: D:\a\sonobus\sonobus\build\SonoBus_artefacts\Release
