name: Build

on:
  push:
    branches:
      - main  # 当在 main 分支上提交代码时触发
  pull_request:
    branches:
      - main  # 当在 main 分支上发起 pull request 时触发

jobs:
  prepare:
    runs-on: windows-latest  # 使用 Windows 操作系统作为构建环境

    steps:
    - name: Checkout repository  # 检出代码仓库
      uses: actions/checkout@v2

    # 安装 CMake
    - name: Install CMake
      run: |
        mkdir cmake
        Invoke-WebRequest -Uri "https://github.com/Kitware/CMake/releases/download/v3.21.0/cmake-3.21.0-windows-x86_64.zip" -OutFile "cmake/cmake.zip"
        Expand-Archive -Path cmake/cmake.zip -DestinationPath cmake
        Add-Content -Path $env:GITHUB_PATH -Value "$(Get-Location)/cmake/bin"
      shell: powershell

    # 设置 Visual Studio 2022
    - name: Set up Visual Studio 2022
      uses: microsoft/setup-msbuild@v1
      with:
        vs-version: 'latest'

    - name: Configure project  # 配置项目
      run: |
        $DEPS = ""

        if (-not [string]::IsNullOrEmpty("${AAX_SDK_PATH}")) {
          echo "Will build AAX plugin"
          $DEPS = "$DEPS -D AAX_SDK_PATH=${AAX_SDK_PATH}"
        }

        if (-not [string]::IsNullOrEmpty("${VST2_SDK_PATH}")) {
          echo "Will build VST2 plugin"
          $DEPS = "$DEPS -D VST2_SDK_PATH=${VST2_SDK_PATH}"
        }

        #cmake -G "Visual Studio 15 2017" -A "x64" $DEPS -B build
        cmake -G "Visual Studio 17 2022" -A "x64" $DEPS -B build
    - name: Build project  # 构建项目
      run: |
        cd D:\a\sonobus\sonobus
        .\buildcmake.sh
