name: Build

on:
  push:
    branches:
      - main  # 当在 main 分支上提交代码时触发
  pull_request:
    branches:
      - main  # 当在 main 分支上发起 pull request 时触发

jobs:
  Build:
    runs-on: windows-latest  # 使用 Windows 操作系统作为构建环境

    steps:
    - name: Checkout repository  # 检出代码仓库
      uses: actions/checkout@v4
    # 设置 VST2_SDK_PATH 环境变量
    - name: Set VST2_SDK_PATH environment variable
      run: |
        echo "VST2_SDK_PATH=${{ github.workspace }}\\VST_SDK\\vst3sdk" >> $GITHUB_ENV


    # 输出所有环境变量以验证是否成功添加
    - name: Output all environment variables
      run: |
        echo "VST2_SDK_PATH: $VST2_SDK_PATH"

    # 安装 CMake
    - name: Install CMake
      run: |
        mkdir cmake
        Invoke-WebRequest -Uri "https://github.com/Kitware/CMake/releases/download/v3.21.0/cmake-3.21.0-windows-x86_64.zip" -OutFile "cmake/cmake.zip"
        Expand-Archive -Path cmake/cmake.zip -DestinationPath cmake
        Add-Content -Path $env:GITHUB_PATH -Value "$(Get-Location)/cmake/bin"
      shell: powershell

    # 设置 Visual Studio 2022
    - name: Set up Visual Studio 2022
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: 'latest'
    
    # 设置 VST2_SDK_PATH 环境变量
    - name: Set VST2_SDK_PATH environment variable
      run: |
        echo "VST2_SDK_PATH=${{ github.workspace }}\VST_SDK\vst3sdk" >> $GITHUB_ENV

    # 输出所有环境变量以验证是否成功添加
    - name: Output all environment variables
      run: |
        echo "VST2_SDK_PATH: $VST2_SDK_PATH"

    # 配置项目
    - name: Configure project
      run: |
        cd D:\a\sonobus\sonobus
        echo "Running setupcmakewin.sh"
        .\setupcmakewin.sh

    # 构建项目
    - name: Build project
      run: |
        cd D:\a\sonobus\sonobus
        echo "Running buildcmake.sh"
        .\buildcmake.sh

    # 上传构建产物
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Release-Artifacts
        path: D:\a\sonobus\sonobus\build\SonoBus_artefacts\Release
